services:
  db:
    image: mongo
    volumes:
      - type: volume
        source: mydb
        target: /data/db
  sever:
    build: .
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./src
        target: /app/src




volumes:
  mydb:
    external: true
      