services:
  db:
    #env_file:
     # - .env
    #environment:
    # - MONGO_INITDB_ROOT_USERNAME=cecile
     # - MONGO_INITDB_ROOT_PASSWORD=123
    image: mongo
    volumes:
      - type: volume
        source: mydb
        target: /data/db
    restart: unless-stopped
  sever:
    environment:
      - MONGO_PWD
      - MONGO_USERNAME
    build: .
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mydb:
    external: true
      