services:
  db:
    #env_file:
     # - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    image: mongo
    volumes:
      - type: volume
        source: mydb
        target: /data/db
  sever:
    build: .
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./src
        target: /app/src

volumes:
  mydb:
    external: true
      