services:
  client:
    build: .
    ports:
      - 3000:3000
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: volume
        target: /home/node/node_modules
  