services:
  client:
    build: .
    ports:
      - 3000:3000
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - type: bind
        source: ./
        target: /home/node
      - type: volume
        target: /home/node/node_modules
  
  test:
    build: .
    volumes:
      - type: bind
        source: ./
        target: /home/node
      - type: volume
        target: /home/node/node_modules
    tty: true
    stdin_open: true
    command: ["npm", "run", "test"]
  
  