services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
  
    volumes:
      - type: bind
        source: ./client
        target: /app
      - type: volume
        target: /home/node_modules
  