services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    environment: 
      NODE_ENV: production
    ports:
      - 80:80
  db:
    image: mongo
    volumes:
      - type: volume
        source: dbprod
        target: /data/db
    env_file:
      - ./db/.env

volumes:
  dbprod:
    external: true
      